metallb:
  chart: metallb
  repository: https://suse-edge.github.io/charts
  version: 0.14.3
endpoint-copier-operator:
  chart: endpoint-copier-operator
  repository: https://suse-edge.github.io/charts
  version: 0.2.0
elemental:
  register-repository: https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging/standard
  system-agent-repository: https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging/standard
